[workspace]
authors = ["jinw00-lee <jil527@ucsd.edu>"]
channels = ["conda-forge"]
name = "kim2024"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.7,<3.14"
jupyterlab = ">=4.4.9,<5"
pandas = ">=2.3.3,<3"
r-base = ">=4.5.1,<4.6"
r-ggplot2 = ">=4.0.0,<5"
r-dplyr = ">=1.1.4,<2"
numpy = ">=2.3.4,<3"
quarto = ">=1.8.25,<2"
ipykernel = ">=6.30.1,<7"
r-irkernel = ">=1.3.2,<2"
r-knitr = ">=1.50,<2"
r-rmarkdown = ">=2.30,<3"
