[workspace]
authors = ["jinw00-lee <jil527@ucsd.edu>"]
channels = ["conda-forge"]
name = "kim2024"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.7,<3.14"
jupyterlab = ">=4.4.9,<5"
pandas = ">=2.3.3,<3"
r-base = ">=4.5.1,<4.6"
r-ggplot2 = ">=4.0.0,<5"
r-dplyr = ">=1.1.4,<2"
numpy = ">=2.3.4,<3"
quarto = ">=1.8.25,<2"
ipykernel = ">=7.1.0,<8"
r-irkernel = ">=1.3.2,<2"
r-knitr = ">=1.50,<2"
r-rmarkdown = ">=2.30,<3"
jupyter = ">=1.1.1,<2"
pytorch = ">=2.8.0,<3"
torchvision = ">=0.24.0,<0.25"
torchaudio = ">=2.8.0,<3"
tqdm = ">=4.67.1,<5"
r-parameters = ">=0.28.2,<0.29"
r-tidyverse = ">=2.0.0,<3"
r-psych = ">=2.5.6,<3"
r-see = ">=0.12.0,<0.13"
r-lavaan = ">=0.6_20,<0.7"
r-performance = ">=0.15.2,<0.16"
r-vegan = ">=2.7_2,<3"
r-jsonlite = ">=2.0.0,<3"
r-reshape = ">=0.8.10,<0.9"
